type NarrativeInput = {
  brand: string;
  pageName: string;
  topic: string;
  audience: string;
  outcome: string;
};

export function buildNarrativeContent(input: NarrativeInput): string[] {
  const { brand, pageName, topic, audience, outcome } = input;

  return [
    `${pageName} at ${brand} is intentionally written for ${audience} who need more than visual inspiration. The goal is to explain how ${topic} decisions connect to business outcomes, stakeholder confidence, and implementation speed. Many agencies present style before strategy, but this section reverses that sequence and starts with decision quality. If an idea looks impressive but fails in execution, it creates cost instead of value. We focus on practical clarity so teams can understand what will be built, why it matters now, and how it supports long-term growth.`,
    `Our process starts by identifying the real problem behind the request. Teams often ask for a new website, a redesign, or a campaign refresh, yet the root issue is frequently positioning confusion, low conversion confidence, weak message hierarchy, or scattered product storytelling. We map the current buyer journey, content structure, and trust signals to isolate what blocks momentum. From there, we define a strategic framework that keeps all future creative choices aligned. This foundation helps reduce revision cycles, protects timeline quality, and ensures the final experience can be measured against meaningful business goals.`,
    `Design direction is then translated into a system that balances identity and usability. We prioritize readable typography, strong spacing rhythm, clear interaction cues, and components that scale across pages without losing personality. Visual polish matters, but consistency matters more because consistency builds trust at speed. We use glass-style layering, purposeful motion, and depth as communication tools rather than decoration. Each element has a job: guide attention, reduce uncertainty, and reinforce value. That disciplined approach helps visitors understand your offer quickly and keeps decision friction low on mobile and desktop alike.`,
    `Development follows the same principle of clarity. We build with maintainable structures so content teams can update pages confidently, marketing teams can launch campaigns faster, and leadership teams can review performance without guessing what changed. Performance, accessibility, and reliability are treated as product requirements, not optional extras. We optimize image handling, simplify render paths, and avoid interaction patterns that look advanced but harm usability. The result is a production-ready platform that supports growth, improves operational efficiency, and creates a stronger foundation for future features.`,
    `Content strategy is where many digital projects lose impact, so we treat it as a first-class deliverable. Every section should answer one of three questions: what you do, why it matters, and what action to take next. We use structured narratives that move from problem context to solution framing and then to proof. This reduces cognitive load and gives your team reusable messaging blocks for sales, ads, and outbound communication. Instead of writing filler text, we write conversion-aware language designed to improve comprehension, reinforce trust, and support action.`,
    `Measurement and iteration are built into the delivery model. Once pages are live, we review behavior signals such as scroll depth, CTA interaction, form completion quality, and entry-to-exit patterns. These insights show where message clarity is working and where users still hesitate. Then we run focused improvements to tighten copy, restructure layout priorities, and strengthen proof placement. This cycle turns design into a growth asset rather than a one-time launch artifact. Over time, it compounds into better lead quality, faster decision-making, and more predictable results.`,
    `Partnership quality matters as much as technical capability. We keep communication direct, timelines visible, and scope decisions transparent so teams can move without confusion. Stakeholders should never wonder what stage a project is in or what decision is needed next. We define milestones, maintain clear review loops, and document rationale for major choices. This creates trust across founders, marketers, product teams, and operations leads. When collaboration is structured, creative work improves because feedback becomes sharper, conflicts decrease, and priorities stay tied to outcomes instead of opinions.`,
    `The intended outcome for this page is simple: clarity that converts. ${brand} builds experiences that are distinctive, practical, and measurable, and ${pageName.toLowerCase()} is designed to demonstrate that standard in detail. If your team is looking for a partner who combines strategic thinking, strong execution, and operational discipline, this is the model we apply from discovery to launch. The objective is ${outcome}, supported by clear messaging, modern design direction, and a production approach that remains dependable as your business scales.`
  ];
}
